name: Ubuntu Recorder
description: Build ubuntu recorder builds
runs:
  using: "composite"
  steps:
    - name: Install alsa
      shell: bash
      run: sudo apt update && sudo apt install libasound2-dev libgtk-3-dev libavcodec-dev libavformat-dev libswscale-dev
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -p neothesia-cli
    - name: Chmod +x
      shell: bash
      run: chmod +x target/release/neothesia-cli
    - name: zip binary
      shell: bash
      run: zip -rj app.zip target/release/neothesia-cli
    - uses: actions/upload-artifact@v4
      with:
        name: ubuntu-recorder-artifact
        path: app.zip
