[workspace]
members = [
    "piano-math",
    "wgpu-jumpstart",
    "neothesia",
    "neothesia-cli",
    "neothesia-core",
    "midi-file",
    "midi-io",
]

default-members = ["neothesia"]
resolver = "2"

[workspace.dependencies]
wgpu = "0.17.1"
glyphon = { git = "https://github.com/grovesNL/glyphon.git", rev = "20f0f8fa80e0d0df4c63634ce9176fa489546ca9" }
log = "0.4"
bytemuck = { version = "1.5", features = ["derive"] }
env_logger = "0.10"
futures = "0.3"
wgpu-jumpstart = { path = "./wgpu-jumpstart" }
neothesia = { path = "./neothesia", default-features = false }
neothesia-core = { path = "./neothesia-core" }
midi-file = { path = "./midi-file" }
piano-math = { path = "./piano-math" }
