[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.0"
zerocopy = "0.3.0"
futures = "0.3.4"
wgpu = "0.5.0"
wgpu_glyph = "0.8.0"
# cgmath = "0.17.0"

log = "0.4"
env_logger = "0.7.1"

tinyfiledialogs = "3.3.9"

# generational-arena = "0.2.7"

# nalgebra = "0.21.0"


lib_midi = {path="./lib_midi"}
midir = "0.5.0"


[build-dependencies]
glsl-to-spirv = "0.1"
