[workspace]
members = [
    "piano-math",
    "wgpu-jumpstart",
    "neothesia",
    "neothesia-cli",
    "neothesia-core",
    "midi-file",
    "midi-io",
]

default-members = ["neothesia"]
resolver = "2"

[workspace.dependencies]
wgpu = "0.18"
glyphon = { git = "https://github.com/grovesNL/glyphon.git", rev = "2caa9fc5e5923c1d827d177c3619cab7e9885b85" }
log = "0.4"
bytemuck = { version = "1.5", features = ["derive"] }
env_logger = "0.10"
futures = "0.3"
wgpu-jumpstart = { path = "./wgpu-jumpstart" }
neothesia = { path = "./neothesia", default-features = false }
neothesia-core = { path = "./neothesia-core" }
midi-file = { path = "./midi-file" }
midi-io = { path = "./midi-io" }
piano-math = { path = "./piano-math" }
