[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[features]
default = ["compile_shader"]
compile_shader = []

[dependencies]
zerocopy = "0.3.0"
futures = "0.3.5"

winit = { version="0.22.1",  features = ["web-sys"]}

wgpu = "0.5.0"
wgpu_glyph = "0.8.0"


log = "0.4"
env_logger = "0.7.1"

tinyfiledialogs = "3.3.9"

lib_midi = {path="./lib_midi"}
midir = "0.6.0"

# js-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# web-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen" }
# console_error_panic_hook = "0.1.6"
# console_log = "0.2.0"

[build-dependencies]
glsl-to-spirv = "0.1"


# [patch.crates-io]
# wgpu = {git ="https://github.com/gfx-rs/wgpu-rs.git"}
# wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
# wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen" }
# web-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }
# js-sys = { git = "https://github.com/rustwasm/wasm-bindgen" }