[workspace]
members = [
  "piano-math",
  "wgpu-jumpstart",
  "neothesia",
  "neothesia-cli",
  "neothesia-core",
  "midi-file",
  "midi-io",
  "neothesia-iced-widgets",
  "nuon",
]

default-members = ["neothesia"]
resolver = "2"

[workspace.dependencies]
wgpu = "0.19"
glyphon = "0.5"
log = "0.4"
bytemuck = { version = "1.5", features = ["derive"] }
env_logger = "0.11"
futures = "0.3"
euclid = "0.22"
wgpu-jumpstart = { path = "./wgpu-jumpstart" }
neothesia = { path = "./neothesia", default-features = false }
neothesia-core = { path = "./neothesia-core" }
neothesia-iced-widgets = { path = "./neothesia-iced-widgets" }

midi-file = { path = "./midi-file" }
midi-io = { path = "./midi-io" }
piano-math = { path = "./piano-math" }
nuon = { path = "./nuon" }

profiling = "1.0"

iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "b9eb86199afe0f2d936eb4ab90af5b2a2c32a87a" }
iced_core = { git = "https://github.com/iced-rs/iced.git", rev = "b9eb86199afe0f2d936eb4ab90af5b2a2c32a87a" }
iced_runtime = { git = "https://github.com/iced-rs/iced.git", rev = "b9eb86199afe0f2d936eb4ab90af5b2a2c32a87a" }
iced_renderer = { git = "https://github.com/iced-rs/iced.git", rev = "b9eb86199afe0f2d936eb4ab90af5b2a2c32a87a" }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "b9eb86199afe0f2d936eb4ab90af5b2a2c32a87a", features = [
  "image",
] }
iced_widget = { git = "https://github.com/iced-rs/iced.git", rev = "b9eb86199afe0f2d936eb4ab90af5b2a2c32a87a", features = [
  "image",
] }
