[workspace]
members = [
  "piano-layout",
  "wgpu-jumpstart",
  "mpeg_encoder",
  "neothesia",
  "neothesia-ai",
  "neothesia-cli",
  "neothesia-core",
  "midi-file",
  "midi-io",
  "neothesia-iced-widgets",
  "nuon",
]

default-members = ["neothesia"]
resolver = "2"

[workspace.dependencies]
wgpu = "22"
glyphon = { git = "https://github.com/hecrj/glyphon.git", rev = "0d7ba1bba4dd71eb88d2cface5ce649db2413cb7" }
# glyphon = "0.5"
log = "0.4"
bytemuck = { version = "1.5", features = ["derive"] }
env_logger = "0.11"
futures = "0.3"
euclid = "0.22"
wgpu-jumpstart = { path = "./wgpu-jumpstart" }
neothesia = { path = "./neothesia", default-features = false }
neothesia-core = { path = "./neothesia-core" }
neothesia-iced-widgets = { path = "./neothesia-iced-widgets" }

midi-file = { path = "./midi-file" }
midi-io = { path = "./midi-io" }
piano-layout = { path = "./piano-layout" }
nuon = { path = "./nuon" }

profiling = "1.0"

iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "142aba2f172c2df2572f6f5b19cdf8b2d565905a" }
iced_core = { git = "https://github.com/iced-rs/iced.git", rev = "142aba2f172c2df2572f6f5b19cdf8b2d565905a" }
iced_runtime = { git = "https://github.com/iced-rs/iced.git", rev = "142aba2f172c2df2572f6f5b19cdf8b2d565905a" }
iced_renderer = { git = "https://github.com/iced-rs/iced.git", rev = "142aba2f172c2df2572f6f5b19cdf8b2d565905a" }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "142aba2f172c2df2572f6f5b19cdf8b2d565905a", features = [
  "image",
] }
iced_widget = { git = "https://github.com/iced-rs/iced.git", rev = "142aba2f172c2df2572f6f5b19cdf8b2d565905a", features = [
  "image",
] }
