[package]
name = "neothesia"
version = "0.0.8"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2021"
default-run = "neothesia"

[workspace]
members = ["lib_midi", "piano_math"]

[features]
default = ["app"]

app = [
    "rfd",
    "fluid-synth",
    "iced_native",
    "iced_wgpu",
    "iced_graphics",
    "iced_style",
]
record = ["mpeg_encoder"]

play_along = []

synth = []
fluid-synth = ["synth", "cpal", "fluidlite"]
oxi-synth = ["synth", "cpal", "oxisynth"]

[dependencies]
bytemuck = "1.5.0"
futures = "0.3.12"

winit = "0.26.0"

wgpu = "0.13.0"
wgpu_glyph = "0.17.0"


log = "0.4.14"
env_logger = "0.9.0"

rfd = { version = "0.8.2", optional = true }

lib_midi = { path = "./lib_midi" }
piano_math = { path = "./piano_math" }
midir = "0.7.0"

fps_ticker = "1.0.0"

iced_native = { git = "https://github.com/iced-rs/iced.git", rev = "66eb6263003c1bbedd1fd14d6b12f172d20a6211", optional = true }
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev = "66eb6263003c1bbedd1fd14d6b12f172d20a6211", features = [
    "png",
], optional = true }
iced_graphics = { git = "https://github.com/iced-rs/iced.git", rev = "66eb6263003c1bbedd1fd14d6b12f172d20a6211", optional = true }
iced_style = { git = "https://github.com/iced-rs/iced.git", rev = "66eb6263003c1bbedd1fd14d6b12f172d20a6211", optional = true }

cpal = { version = "0.13.1", optional = true }
fluidlite = { version = "0.2.1", features = ["builtin"], optional = true }
oxisynth = { git = "https://github.com/PolyMeilex/OxiSynth.git", optional = true }

ron = "0.7.0"
serde = { version = "1.0.123", features = ["serde_derive"] }

mpeg_encoder = { git = "https://github.com/PolyMeilex/mpeg_encoder_next.git", optional = true }
midi = "0.1.0"
num = "0.4.0"
# mpeg_encoder = {path="../mpeg_encoder_next", optional=true}

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

[[bin]]
name = "neothesia-cli"
required-features = ["record"]

[[bin]]
name = "neothesia"
required-features = ["app"]
