[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[dependencies]
zerocopy = "0.3.0"
futures = "0.3.4"

# TODO: Update to 0.22 after https://github.com/Gekkio/imgui-rs/pull/309
winit = "0.21.0"

wgpu = "0.5.0"
wgpu_glyph = "0.8.0"


log = "0.4"
env_logger = "0.7.1"

tinyfiledialogs = "3.3.9"

# generational-arena = "0.2.7"


lib_midi = {path="./lib_midi"}
midir = "0.5.0"


[build-dependencies]
glsl-to-spirv = "0.1"