[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2021"
default-run = "neothesia"

[features]
default = ["oxi-synth"]

synth = []
fluid-synth = ["synth", "cpal", "fluidlite", "oxisynth"]
oxi-synth = ["synth", "cpal", "oxisynth"]

[dependencies]
futures = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
fps_ticker = "1.0"
ron = "0.8"
serde = { version = "1.0", features = ["serde_derive"] }
num = "0.4"

wgpu = { workspace = true }
wgpu-jumpstart = { workspace = true }

neothesia-core = { workspace = true }
piano-math = { workspace = true }

winit = "0.28.2"
rfd = "0.11.2"
async-thread = "0.1"

cpal = { version = "0.15.0", optional = true }
fluidlite = { version = "0.2", features = ["builtin"], optional = true }
oxisynth = { version = "0.0.3", optional = true }

midi-file = { workspace = true }
midi-io = { path = "../midi-io" }

iced_style = {git = "https://github.com/iced-rs/iced.git", rev="bc9bb28b1ccd1248d63ccdfef2f57d7aa837abbb"}
iced_graphics = {git = "https://github.com/iced-rs/iced.git", rev="bc9bb28b1ccd1248d63ccdfef2f57d7aa837abbb"}
iced_core = {git = "https://github.com/iced-rs/iced.git", rev="bc9bb28b1ccd1248d63ccdfef2f57d7aa837abbb"}
iced_runtime = {git = "https://github.com/iced-rs/iced.git", rev="bc9bb28b1ccd1248d63ccdfef2f57d7aa837abbb"}
iced_wgpu = { git = "https://github.com/iced-rs/iced.git", rev="bc9bb28b1ccd1248d63ccdfef2f57d7aa837abbb", features = ["image"] }
iced_widget = { git = "https://github.com/iced-rs/iced.git", rev="bc9bb28b1ccd1248d63ccdfef2f57d7aa837abbb", features = ["image"] }

[[bin]]
name = "neothesia"
