[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/PolyMeilex/mpeg_encoder_next.git"]
git = "https://github.com/PolyMeilex/mpeg_encoder_next.git"
replace-with = "vendored-sources"

[source."git+https://github.com/grovesNL/glyphon.git?rev=2caa9fc5e5923c1d827d177c3619cab7e9885b85"]
git = "https://github.com/grovesNL/glyphon.git"
rev = "2caa9fc5e5923c1d827d177c3619cab7e9885b85"
replace-with = "vendored-sources"

[source."git+https://github.com/iced-rs/iced.git?rev=fc285d3e461626408c56bbc1605fcf0c974b2f69"]
git = "https://github.com/iced-rs/iced.git"
rev = "fc285d3e461626408c56bbc1605fcf0c974b2f69"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
