name: Windows
description: Build Windows builds

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: powershell
      run: |
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Invoke-WebRequest "${env:FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
        7z x ffmpeg-release-full-shared.7z
        mkdir ffmpeg
        mv ffmpeg-*/* ffmpeg/
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
        Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"

    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release -p neothesia-cli
    - uses: actions/upload-artifact@v4
      with:
        name: windows-recorder-artifact
        path: target/release/neothesia-cli.exe
