name: Windows
description: Build Windows builds
runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable
    - name: Build Windows Release
      shell: bash
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: target/release/neothesia.exe
